// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrder = "orders"

// Order 订单表
type Order struct {
	ID        int64          `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:ID" json:"id"`                             // ID
	OrderID   string         `gorm:"column:order_id;type:char(32);not null;comment:订单id" json:"order_id"`                               // 订单id
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;not null;comment:更新时间" json:"updated_at"`                           // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
